all: pipe1 pipe2 pipe3 pipe4 pipe5 pipe6

clean:
	rm -f pipe1 pipe2 pipe3 pipe4 pipe5 pipe6

pipe1: pipe1.c
	gcc -o pipe1 pipe1.c -Wall

pipe2: pipe2.c
	gcc -o pipe2 pipe2.c -Wall

pipe3: pipe3.c
	gcc -o pipe3 pipe3.c -Wall

pipe4: pipe4.c
	gcc -o pipe4 pipe4.c -Wall

pipe5: pipe5.c
	gcc -o pipe5 pipe5.c -Wall

pipe6: pipe6.c
	gcc -o pipe6 pipe6.c -Wall

